# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\eerla\OneDrive\Desktop\OASIS\Random-Password-Generator\generated-files/ui/new_RRG.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.app_controller import AppController

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 641)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Menu_Panel = QCustomSlideMenu(self.centralwidget)
        self.Menu_Panel.setMinimumSize(QtCore.QSize(250, 630))
        self.Menu_Panel.setMaximumSize(QtCore.QSize(250, 630))
        self.Menu_Panel.setStyleSheet("QWidget {\n"
"    background-color: #141C24  ;\n"
"\n"
"}\n"
"")
        self.Menu_Panel.setObjectName("Menu_Panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Menu_Panel)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_Icon = QtWidgets.QFrame(self.Menu_Panel)
        self.Main_Icon.setMinimumSize(QtCore.QSize(0, 80))
        self.Main_Icon.setStyleSheet("QFrame {\n"
"    background-color: #394B5A  ;\n"
"    border:1px solid #ececec   ;\n"
"}\n"
"QLabel{\n"
"color:white;\n"
"}\n"
"#Main_Icon{\n"
"border:1px solid black;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.Main_Icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_Icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_Icon.setObjectName("Main_Icon")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.Main_Icon)
        self.horizontalLayout_10.setContentsMargins(6, 0, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.App_icon = QtWidgets.QLabel(self.Main_Icon)
        self.App_icon.setMinimumSize(QtCore.QSize(40, 40))
        self.App_icon.setMaximumSize(QtCore.QSize(40, 40))
        self.App_icon.setStyleSheet("QFrame {\n"
"    border: 0px solid black;\n"
"}\n"
"")
        self.App_icon.setText("")
        self.App_icon.setPixmap(QtGui.QPixmap(":/icons/Icons/feather/unlock.png"))
        self.App_icon.setScaledContents(True)
        self.App_icon.setObjectName("App_icon")
        self.horizontalLayout_10.addWidget(self.App_icon, 0, QtCore.Qt.AlignVCenter)
        self.Name_of_app = QtWidgets.QLabel(self.Main_Icon)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Name_of_app.setFont(font)
        self.Name_of_app.setStyleSheet("QFrame {\n"
"    border: 0px solid black;\n"
"}\n"
"")
        self.Name_of_app.setObjectName("Name_of_app")
        self.horizontalLayout_10.addWidget(self.Name_of_app)
        self.verticalLayout.addWidget(self.Main_Icon, 0, QtCore.Qt.AlignTop)
        self.navigation_buttons = QtWidgets.QFrame(self.Menu_Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navigation_buttons.sizePolicy().hasHeightForWidth())
        self.navigation_buttons.setSizePolicy(sizePolicy)
        self.navigation_buttons.setMinimumSize(QtCore.QSize(100, 0))
        self.navigation_buttons.setStyleSheet("QFrame {\n"
"    background-color: #25303C  ;\n"
"border:2px solid #25303C   ;\n"
"padding:10px;\n"
"}\n"
"QPushButton{\n"
"    background-color:#141C24;\n"
"    border : 2px solid #A0C1D6;\n"
"    padding:15px;\n"
"    border-radius:10px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #394B5A;\n"
"}\n"
"#navigation_buttons{\n"
"border-top:1px solid black;\n"
"border-right:1px solid black;\n"
"border-left:1px solid black;\n"
"}\n"
"")
        self.navigation_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navigation_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navigation_buttons.setObjectName("navigation_buttons")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.navigation_buttons)
        self.verticalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Sign_Up_btn = QtWidgets.QPushButton(self.navigation_buttons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sign_Up_btn.setFont(font)
        self.Sign_Up_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/feather/user-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Sign_Up_btn.setIcon(icon)
        self.Sign_Up_btn.setObjectName("Sign_Up_btn")
        self.verticalLayout_2.addWidget(self.Sign_Up_btn)
        self.Login_In_btn = QtWidgets.QPushButton(self.navigation_buttons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Login_In_btn.setFont(font)
        self.Login_In_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/feather/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Login_In_btn.setIcon(icon1)
        self.Login_In_btn.setAutoDefault(False)
        self.Login_In_btn.setObjectName("Login_In_btn")
        self.verticalLayout_2.addWidget(self.Login_In_btn)
        self.Create_pass_btn = QtWidgets.QPushButton(self.navigation_buttons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Create_pass_btn.setFont(font)
        self.Create_pass_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/feather/key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Create_pass_btn.setIcon(icon2)
        self.Create_pass_btn.setObjectName("Create_pass_btn")
        self.verticalLayout_2.addWidget(self.Create_pass_btn)
        self.Check_pass_btn = QtWidgets.QPushButton(self.navigation_buttons)
        self.Check_pass_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/feather/check-square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Check_pass_btn.setIcon(icon3)
        self.Check_pass_btn.setObjectName("Check_pass_btn")
        self.verticalLayout_2.addWidget(self.Check_pass_btn)
        self.History_btn = QtWidgets.QPushButton(self.navigation_buttons)
        self.History_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/feather/hard-drive.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.History_btn.setIcon(icon4)
        self.History_btn.setObjectName("History_btn")
        self.verticalLayout_2.addWidget(self.History_btn)
        self.About_btn = QtWidgets.QPushButton(self.navigation_buttons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.About_btn.setFont(font)
        self.About_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons/feather/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.About_btn.setIcon(icon5)
        self.About_btn.setObjectName("About_btn")
        self.verticalLayout_2.addWidget(self.About_btn)
        self.verticalLayout.addWidget(self.navigation_buttons)
        self.Referral_websites = QtWidgets.QFrame(self.Menu_Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Referral_websites.sizePolicy().hasHeightForWidth())
        self.Referral_websites.setSizePolicy(sizePolicy)
        self.Referral_websites.setStyleSheet("QFrame {\n"
"    background-color: #25303C  ;\n"
"    border:1px solid #25303C   ;\n"
"}\n"
"#Referral_websites{\n"
"border-bottom:1px solid black;\n"
"border-right:1px solid black;\n"
"border-left:1px solid black;\n"
"}\n"
"QPushButton{\n"
"    background-color:#141C24;\n"
"    border:2px solid #A0C1D6;\n"
"    padding:5px;\n"
"    border-radius:10px;\n"
"color:white;\n"
"margin:5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #394B5A;\n"
"}")
        self.Referral_websites.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Referral_websites.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Referral_websites.setObjectName("Referral_websites")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Referral_websites)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Github_Referral = QtWidgets.QFrame(self.Referral_websites)
        self.Github_Referral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Github_Referral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Github_Referral.setObjectName("Github_Referral")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.Github_Referral)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.icon_Github = QtWidgets.QLabel(self.Github_Referral)
        self.icon_Github.setMinimumSize(QtCore.QSize(60, 60))
        self.icon_Github.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.icon_Github.setFont(font)
        self.icon_Github.setStyleSheet("QFrame {\n"
"    border: 0px solid black;\n"
"}\n"
"")
        self.icon_Github.setText("")
        self.icon_Github.setPixmap(QtGui.QPixmap(":/images/Images/github-mark-white.png"))
        self.icon_Github.setScaledContents(True)
        self.icon_Github.setObjectName("icon_Github")
        self.horizontalLayout_11.addWidget(self.icon_Github, 0, QtCore.Qt.AlignVCenter)
        self.Name_Github = QtWidgets.QLabel(self.Github_Referral)
        self.Name_Github.setMinimumSize(QtCore.QSize(90, 40))
        self.Name_Github.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Name_Github.setFont(font)
        self.Name_Github.setStyleSheet("QFrame {\n"
"    border: 0px solid black;\n"
"}\n"
"")
        self.Name_Github.setText("")
        self.Name_Github.setPixmap(QtGui.QPixmap(":/images/Images/GitHub_Logo_White.png"))
        self.Name_Github.setScaledContents(True)
        self.Name_Github.setObjectName("Name_Github")
        self.horizontalLayout_11.addWidget(self.Name_Github, 0, QtCore.Qt.AlignVCenter)
        self.GitHub_link = QtWidgets.QPushButton(self.Github_Referral)
        self.GitHub_link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GitHub_link.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons/feather/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GitHub_link.setIcon(icon6)
        self.GitHub_link.setObjectName("GitHub_link")
        self.horizontalLayout_11.addWidget(self.GitHub_link, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.Github_Referral, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.LinkedIn_Referral = QtWidgets.QFrame(self.Referral_websites)
        self.LinkedIn_Referral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LinkedIn_Referral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LinkedIn_Referral.setObjectName("LinkedIn_Referral")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.LinkedIn_Referral)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.icon_Linkedin = QtWidgets.QLabel(self.LinkedIn_Referral)
        self.icon_Linkedin.setMinimumSize(QtCore.QSize(0, 40))
        self.icon_Linkedin.setMaximumSize(QtCore.QSize(140, 40))
        self.icon_Linkedin.setStyleSheet("QFrame {\n"
"    border: 0px solid black;\n"
"}\n"
"")
        self.icon_Linkedin.setText("")
        self.icon_Linkedin.setPixmap(QtGui.QPixmap(":/images/Images/LinkedIn_2021.svg"))
        self.icon_Linkedin.setScaledContents(True)
        self.icon_Linkedin.setObjectName("icon_Linkedin")
        self.horizontalLayout_12.addWidget(self.icon_Linkedin, 0, QtCore.Qt.AlignHCenter)
        self.LinkedIn_Link = QtWidgets.QPushButton(self.LinkedIn_Referral)
        self.LinkedIn_Link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LinkedIn_Link.setText("")
        self.LinkedIn_Link.setIcon(icon6)
        self.LinkedIn_Link.setObjectName("LinkedIn_Link")
        self.horizontalLayout_12.addWidget(self.LinkedIn_Link, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.LinkedIn_Referral, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.Referral_websites, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.Menu_Panel)
        self.Main_Panel = QtWidgets.QWidget(self.centralwidget)
        self.Main_Panel.setStyleSheet("\n"
"QFrame {\n"
"    border: 2px solid black;\n"
"    background-color:#141C24;\n"
"}\n"
"")
        self.Main_Panel.setObjectName("Main_Panel")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Main_Panel)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Title_bar = QtWidgets.QFrame(self.Main_Panel)
        self.Title_bar.setMinimumSize(QtCore.QSize(565, 80))
        self.Title_bar.setStyleSheet("QFrame {\n"
"    background-color: #394B5A  ;\n"
"border:0px;\n"
"}\n"
"QLabel{\n"
"color:white;\n"
"}\n"
"\n"
"#Title_bar{\n"
"border:1px solid black;\n"
"\n"
"}\n"
"QPushButton {\n"
"height:50px;\n"
"width:50px;\n"
"border-radius: 20px;\n"
"padding:15px;\n"
"margin: 2px;\n"
"border : 2px solid #A0C1D6;\n"
"background-color:#141C24;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #394B5A;\n"
"}")
        self.Title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title_bar.setObjectName("Title_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Title_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Menu_Restore_close = QtWidgets.QFrame(self.Title_bar)
        self.Menu_Restore_close.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menu_Restore_close.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu_Restore_close.setObjectName("Menu_Restore_close")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Menu_Restore_close)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Menu_Close_btn = QtWidgets.QPushButton(self.Menu_Restore_close)
        self.Menu_Close_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.Menu_Close_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.Menu_Close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Menu_Close_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icons/feather/chevrons-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Menu_Close_btn.setIcon(icon7)
        self.Menu_Close_btn.setObjectName("Menu_Close_btn")
        self.horizontalLayout_3.addWidget(self.Menu_Close_btn)
        self.Name_Menu = QtWidgets.QLabel(self.Menu_Restore_close)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Name_Menu.setFont(font)
        self.Name_Menu.setLineWidth(1)
        self.Name_Menu.setObjectName("Name_Menu")
        self.horizontalLayout_3.addWidget(self.Name_Menu)
        self.horizontalLayout_2.addWidget(self.Menu_Restore_close)
        self.DashBoard = QtWidgets.QFrame(self.Title_bar)
        self.DashBoard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DashBoard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DashBoard.setObjectName("DashBoard")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.DashBoard)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Name = QtWidgets.QLabel(self.DashBoard)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Name.setFont(font)
        self.Name.setObjectName("Name")
        self.verticalLayout_5.addWidget(self.Name, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.DashBoard)
        self.Window_buttons = QtWidgets.QFrame(self.Title_bar)
        self.Window_buttons.setStyleSheet("QPushButton{\n"
"padding :20px;\n"
"}")
        self.Window_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Window_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Window_buttons.setObjectName("Window_buttons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Window_buttons)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Minimize_button = QtWidgets.QPushButton(self.Window_buttons)
        self.Minimize_button.setMinimumSize(QtCore.QSize(50, 50))
        self.Minimize_button.setMaximumSize(QtCore.QSize(50, 50))
        self.Minimize_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Minimize_button.setMouseTracking(True)
        self.Minimize_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Icons/feather/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Minimize_button.setIcon(icon8)
        self.Minimize_button.setObjectName("Minimize_button")
        self.horizontalLayout_4.addWidget(self.Minimize_button)
        self.Maximize_Restore_button = QtWidgets.QPushButton(self.Window_buttons)
        self.Maximize_Restore_button.setMinimumSize(QtCore.QSize(50, 50))
        self.Maximize_Restore_button.setMaximumSize(QtCore.QSize(50, 50))
        self.Maximize_Restore_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Maximize_Restore_button.setStyleSheet("")
        self.Maximize_Restore_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Icons/feather/maximize-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Maximize_Restore_button.setIcon(icon9)
        self.Maximize_Restore_button.setObjectName("Maximize_Restore_button")
        self.horizontalLayout_4.addWidget(self.Maximize_Restore_button)
        self.Close_button = QtWidgets.QPushButton(self.Window_buttons)
        self.Close_button.setMinimumSize(QtCore.QSize(50, 50))
        self.Close_button.setMaximumSize(QtCore.QSize(50, 50))
        self.Close_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Close_button.setMouseTracking(False)
        self.Close_button.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Icons/feather/window_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close_button.setIcon(icon10)
        self.Close_button.setAutoDefault(False)
        self.Close_button.setObjectName("Close_button")
        self.horizontalLayout_4.addWidget(self.Close_button)
        self.horizontalLayout_2.addWidget(self.Window_buttons, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.Title_bar)
        self.Main_body = QtWidgets.QFrame(self.Main_Panel)
        self.Main_body.setStyleSheet("QLabel{\n"
"color:white;\n"
"}\n"
"QFrame {\n"
"    background-color: #141C24  ;\n"
"border:0px;\n"
"\n"
"}\n"
"QWidget {\n"
"    background-color: #141C24  ;\n"
"}\n"
"")
        self.Main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_body.setObjectName("Main_body")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Main_body)
        self.verticalLayout_8.setContentsMargins(-1, -1, -1, 8)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_7 = QtWidgets.QFrame(self.Main_body)
        self.frame_7.setStyleSheet("QLabel{\n"
"    border-radius: 10px;\n"
"    border: 0px;\n"
"    padding: 5px;\n"
"}\n"
"#UserName_Display{\n"
"border:0px;}\n"
"QFrame{\n"
"    border-radius: 10px;\n"
"    border: 2px solid  white;\n"
"    padding: 5px;\n"
"color:white;}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.UserName_Display = QtWidgets.QLabel(self.frame_7)
        self.UserName_Display.setObjectName("UserName_Display")
        self.verticalLayout_17.addWidget(self.UserName_Display, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_8.addWidget(self.frame_7, 0, QtCore.Qt.AlignRight)
        self.stackedWidget = QtWidgets.QStackedWidget(self.Main_body)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 187, 187, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 187, 187, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 187, 187, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.stackedWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Sign_Up_Page = QtWidgets.QWidget()
        self.Sign_Up_Page.setObjectName("Sign_Up_Page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Sign_Up_Page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_14 = QtWidgets.QFrame(self.Sign_Up_Page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.frame_14.setFont(font)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(self.frame_14)
        self.frame.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    border: 2px solid  white;\n"
"    padding: 5px;\n"
"color:white;}\n"
"QLabel{\n"
"border:0px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(40, 40))
        self.label_5.setMaximumSize(QtCore.QSize(40, 40))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/Icons/feather/user-plus.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_18.addWidget(self.label_5)
        self.label_12 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12)
        self.horizontalLayout_6.addWidget(self.frame)
        self.verticalLayout_10.addWidget(self.frame_14, 0, QtCore.Qt.AlignHCenter)
        self.frame_15 = QtWidgets.QFrame(self.Sign_Up_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_15.setPalette(palette)
        self.frame_15.setStyleSheet("#Sign_Up_info_after_check{\n"
"border:0px;\n"
"}\n"
"QPushButton{\n"
"    border:2px solid black;\n"
"}\n"
"\n"
"QLabel,QPushButton{\n"
"    border-radius: 10px;\n"
"    border: 2px solid  white;\n"
"    padding: 10px;\n"
"color:white;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid  white;\n"
"}\n"
"QLineEdit {\n"
"    border-radius: 10px;\n"
"    border: 2px solid #ccc;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #394B5A;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: hsl(0, 0%, 30%);\n"
"}\n"
"")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Sign_Up_Page_2 = QtWidgets.QFrame(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sign_Up_Page_2.sizePolicy().hasHeightForWidth())
        self.Sign_Up_Page_2.setSizePolicy(sizePolicy)
        self.Sign_Up_Page_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Sign_Up_Page_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Sign_Up_Page_2.setObjectName("Sign_Up_Page_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.Sign_Up_Page_2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.Sign_Up_Info_Box = QtWidgets.QFrame(self.Sign_Up_Page_2)
        self.Sign_Up_Info_Box.setStyleSheet("#Sign_Up_Info_Box{\n"
"    border-radius: 10px;\n"
"    border: 2px solid  white;\n"
"    padding: 5px;\n"
"color:white;\n"
"}")
        self.Sign_Up_Info_Box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Sign_Up_Info_Box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Sign_Up_Info_Box.setObjectName("Sign_Up_Info_Box")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.Sign_Up_Info_Box)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.User_info_box = QtWidgets.QFrame(self.Sign_Up_Info_Box)
        self.User_info_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.User_info_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.User_info_box.setObjectName("User_info_box")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.User_info_box)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(self.User_info_box)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        self.User_Info_Input = QtWidgets.QLineEdit(self.User_info_box)
        self.User_Info_Input.setObjectName("User_Info_Input")
        self.horizontalLayout_14.addWidget(self.User_Info_Input)
        self.verticalLayout_15.addWidget(self.User_info_box, 0, QtCore.Qt.AlignHCenter)
        self.EMail_box = QtWidgets.QFrame(self.Sign_Up_Info_Box)
        self.EMail_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.EMail_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.EMail_box.setObjectName("EMail_box")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.EMail_box)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_4 = QtWidgets.QLabel(self.EMail_box)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_17.addWidget(self.label_4)
        self.EMail_input = QtWidgets.QLineEdit(self.EMail_box)
        self.EMail_input.setText("")
        self.EMail_input.setObjectName("EMail_input")
        self.horizontalLayout_17.addWidget(self.EMail_input)
        self.verticalLayout_15.addWidget(self.EMail_box, 0, QtCore.Qt.AlignHCenter)
        self.Pass_box = QtWidgets.QFrame(self.Sign_Up_Info_Box)
        self.Pass_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Pass_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Pass_box.setObjectName("Pass_box")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.Pass_box)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.Pass_box)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_15.addWidget(self.label_2)
        self.Pass_input = QtWidgets.QLineEdit(self.Pass_box)
        self.Pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Pass_input.setObjectName("Pass_input")
        self.horizontalLayout_15.addWidget(self.Pass_input)
        self.verticalLayout_15.addWidget(self.Pass_box, 0, QtCore.Qt.AlignHCenter)
        self.ReEnter_pass_box = QtWidgets.QFrame(self.Sign_Up_Info_Box)
        self.ReEnter_pass_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ReEnter_pass_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ReEnter_pass_box.setObjectName("ReEnter_pass_box")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.ReEnter_pass_box)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_3 = QtWidgets.QLabel(self.ReEnter_pass_box)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_16.addWidget(self.label_3)
        self.Re_enter_pass_input = QtWidgets.QLineEdit(self.ReEnter_pass_box)
        self.Re_enter_pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Re_enter_pass_input.setObjectName("Re_enter_pass_input")
        self.horizontalLayout_16.addWidget(self.Re_enter_pass_input)
        self.verticalLayout_15.addWidget(self.ReEnter_pass_box, 0, QtCore.Qt.AlignHCenter)
        self.Sign_up_btn = QtWidgets.QPushButton(self.Sign_Up_Info_Box)
        self.Sign_up_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Sign_up_btn.setIcon(icon)
        self.Sign_up_btn.setObjectName("Sign_up_btn")
        self.verticalLayout_15.addWidget(self.Sign_up_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_16.addWidget(self.Sign_Up_Info_Box, 0, QtCore.Qt.AlignHCenter)
        self.Sign_Up_info_after_check = QtWidgets.QLabel(self.Sign_Up_Page_2)
        self.Sign_Up_info_after_check.setText("")
        self.Sign_Up_info_after_check.setObjectName("Sign_Up_info_after_check")
        self.verticalLayout_16.addWidget(self.Sign_Up_info_after_check, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_14.addWidget(self.Sign_Up_Page_2)
        self.verticalLayout_10.addWidget(self.frame_15)
        self.stackedWidget.addWidget(self.Sign_Up_Page)
        self.Login_In_Page = QtWidgets.QWidget()
        self.Login_In_Page.setObjectName("Login_In_Page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Login_In_Page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_16 = QtWidgets.QFrame(self.Login_In_Page)
        self.frame_16.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    border: 2px solid  white;\n"
"color:white;}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_3 = QtWidgets.QFrame(self.frame_16)
        self.frame_3.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    border: 2px solid  hsl(0, 0%, 10%);;\n"
"    padding: 5px;\n"
"}\n"
"QLabel{\n"
"border:0px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setMinimumSize(QtCore.QSize(40, 40))
        self.label_8.setMaximumSize(QtCore.QSize(40, 40))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/icons/fd5028/feather/user.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_21.addWidget(self.label_8)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("")
        self.label_15.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_21.addWidget(self.label_15)
        self.verticalLayout_18.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_11.addWidget(self.frame_16, 0, QtCore.Qt.AlignHCenter)
        self.frame_17 = QtWidgets.QFrame(self.Login_In_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setStyleSheet("QFrame,#Login_info_after_check{\n"
"border:0px;\n"
"}\n"
"#Pass_input_login::placeholder {\n"
"    color: #BBBBBB; /* This sets the placeholder color to a duller white */\n"
"}\n"
"QPushButton{\n"
"    border:2px solid white;\n"
"}\n"
"\n"
"QLabel,QPushButton,#Login_Box{\n"
"    border-radius: 10px;\n"
"    border: 2px solid  white;\n"
"    padding: 10px;\n"
"color:white;\n"
"}\n"
"QLineEdit {\n"
"    border-radius: 10px;\n"
"    border: 2px solid #ccc;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #394B5A;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: hsl(0, 0%, 30%);\n"
"}\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_21.setContentsMargins(-1, 28, -1, 10)
        self.verticalLayout_21.setSpacing(6)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.Login_Box = QtWidgets.QFrame(self.frame_17)
        self.Login_Box.setStyleSheet("#Sign_Up_Info_Box{\n"
"\n"
"    border-radius: 10px;\n"
"    border: 2px solid  hsl(0, 0%, 10%);;\n"
"    padding: 5px;\n"
"}")
        self.Login_Box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Login_Box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Login_Box.setObjectName("Login_Box")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.Login_Box)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.UserName_box_login = QtWidgets.QFrame(self.Login_Box)
        self.UserName_box_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UserName_box_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UserName_box_login.setObjectName("UserName_box_login")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.UserName_box_login)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_18 = QtWidgets.QLabel(self.UserName_box_login)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_25.addWidget(self.label_18)
        self.Username_input_login = QtWidgets.QLineEdit(self.UserName_box_login)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Username_input_login.setPalette(palette)
        self.Username_input_login.setObjectName("Username_input_login")
        self.horizontalLayout_25.addWidget(self.Username_input_login)
        self.verticalLayout_20.addWidget(self.UserName_box_login, 0, QtCore.Qt.AlignHCenter)
        self.Password_box_login = QtWidgets.QFrame(self.Login_Box)
        self.Password_box_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Password_box_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Password_box_login.setObjectName("Password_box_login")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.Password_box_login)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_20 = QtWidgets.QLabel(self.Password_box_login)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_27.addWidget(self.label_20)
        self.Pass_input_login = QtWidgets.QLineEdit(self.Password_box_login)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Pass_input_login.setPalette(palette)
        self.Pass_input_login.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Pass_input_login.setObjectName("Pass_input_login")
        self.horizontalLayout_27.addWidget(self.Pass_input_login)
        self.verticalLayout_20.addWidget(self.Password_box_login, 0, QtCore.Qt.AlignHCenter)
        self.Login_Check_btn = QtWidgets.QPushButton(self.Login_Box)
        self.Login_Check_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/fd5028/feather/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Login_Check_btn.setIcon(icon11)
        self.Login_Check_btn.setObjectName("Login_Check_btn")
        self.verticalLayout_20.addWidget(self.Login_Check_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_21.addWidget(self.Login_Box, 0, QtCore.Qt.AlignHCenter)
        self.Login_info_after_check = QtWidgets.QLabel(self.frame_17)
        self.Login_info_after_check.setText("")
        self.Login_info_after_check.setObjectName("Login_info_after_check")
        self.verticalLayout_21.addWidget(self.Login_info_after_check, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_11.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.Login_In_Page)
        self.Create_pass = QtWidgets.QWidget()
        self.Create_pass.setObjectName("Create_pass")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Create_pass)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_18 = QtWidgets.QFrame(self.Create_pass)
        self.frame_18.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    border: 2px solid  white;\n"
"    padding: 5px;\n"
"color:white;}\n"
"QLabel{\n"
"border:0px;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_18)
        self.label_7.setMinimumSize(QtCore.QSize(40, 40))
        self.label_7.setMaximumSize(QtCore.QSize(40, 40))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/icons/Icons/feather/key.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_12.addWidget(self.frame_18, 0, QtCore.Qt.AlignHCenter)
        self.frame_19 = QtWidgets.QFrame(self.Create_pass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_19.sizePolicy().hasHeightForWidth())
        self.frame_19.setSizePolicy(sizePolicy)
        self.frame_19.setStyleSheet("QFrame,QComboBox,QLineEdit,QPushButton,QCheckBox {\n"
"border:0px solid white;\n"
"color:white;}\n"
"#Easy_comboBox,#Med_comboBox,#Hard_comboBox,#VHard_comboBox,#Label_input_pass,#Complexity_label_main,#frame_2,#frame_8{\n"
"border:2px solid white;\n"
"border-radius:10px;\n"
"color:white;\n"
"}\n"
"#Pass_complexity{\n"
"border:2px solid white;\n"
"border-radius:7px;\n"
"padding: 10px;\n"
"}\n"
"QLabel{\n"
"padding: 10px;\n"
"border-radius:10px;\n"
"}\n"
"QLineEdit {\n"
"    border-radius: 10px;\n"
"    border: 2px solid #ccc;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton{\n"
"    background-color:#141C24;\n"
"    border : 2px solid #00FFFF;\n"
"    padding:5px;\n"
"    border-radius:10px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #394B5A;\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_2 = QtWidgets.QFrame(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.Label_input_pass = QtWidgets.QLabel(self.frame_9)
        self.Label_input_pass.setObjectName("Label_input_pass")
        self.horizontalLayout_22.addWidget(self.Label_input_pass, 0, QtCore.Qt.AlignVCenter)
        self.Input_pass_Lineedit = QtWidgets.QLineEdit(self.frame_9)
        self.Input_pass_Lineedit.setObjectName("Input_pass_Lineedit")
        self.horizontalLayout_22.addWidget(self.Input_pass_Lineedit)
        self.verticalLayout_24.addWidget(self.frame_9, 0, QtCore.Qt.AlignLeft)
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.Complexity_label_main = QtWidgets.QLabel(self.frame_10)
        self.Complexity_label_main.setStyleSheet("border-radius:10px;")
        self.Complexity_label_main.setObjectName("Complexity_label_main")
        self.horizontalLayout_23.addWidget(self.Complexity_label_main, 0, QtCore.Qt.AlignVCenter)
        self.Pass_complexity = QtWidgets.QComboBox(self.frame_10)
        self.Pass_complexity.setMinimumSize(QtCore.QSize(90, 0))
        self.Pass_complexity.setMaximumSize(QtCore.QSize(90, 16777215))
        self.Pass_complexity.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Pass_complexity.setObjectName("Pass_complexity")
        self.Pass_complexity.addItem("")
        self.Pass_complexity.addItem("")
        self.Pass_complexity.addItem("")
        self.Pass_complexity.addItem("")
        self.horizontalLayout_23.addWidget(self.Pass_complexity)
        self.verticalLayout_24.addWidget(self.frame_10, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_20.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.Easy_comboBox = QtWidgets.QFrame(self.frame_5)
        self.Easy_comboBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Easy_comboBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Easy_comboBox.setObjectName("Easy_comboBox")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.Easy_comboBox)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.Easy_char_box = QtWidgets.QCheckBox(self.Easy_comboBox)
        self.Easy_char_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Easy_char_box.setObjectName("Easy_char_box")
        self.verticalLayout_26.addWidget(self.Easy_char_box)
        self.verticalLayout_25.addWidget(self.Easy_comboBox)
        self.Med_comboBox = QtWidgets.QFrame(self.frame_5)
        self.Med_comboBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Med_comboBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Med_comboBox.setObjectName("Med_comboBox")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.Med_comboBox)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.Medium_char_box = QtWidgets.QCheckBox(self.Med_comboBox)
        self.Medium_char_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Medium_char_box.setObjectName("Medium_char_box")
        self.verticalLayout_27.addWidget(self.Medium_char_box)
        self.verticalLayout_25.addWidget(self.Med_comboBox)
        self.Hard_comboBox = QtWidgets.QFrame(self.frame_5)
        self.Hard_comboBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Hard_comboBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Hard_comboBox.setObjectName("Hard_comboBox")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.Hard_comboBox)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.Hard_char_box = QtWidgets.QCheckBox(self.Hard_comboBox)
        self.Hard_char_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Hard_char_box.setObjectName("Hard_char_box")
        self.verticalLayout_28.addWidget(self.Hard_char_box)
        self.verticalLayout_25.addWidget(self.Hard_comboBox)
        self.VHard_comboBox = QtWidgets.QFrame(self.frame_5)
        self.VHard_comboBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VHard_comboBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VHard_comboBox.setObjectName("VHard_comboBox")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.VHard_comboBox)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.VHard_char_box = QtWidgets.QCheckBox(self.VHard_comboBox)
        self.VHard_char_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VHard_char_box.setObjectName("VHard_char_box")
        self.verticalLayout_29.addWidget(self.VHard_char_box)
        self.verticalLayout_25.addWidget(self.VHard_comboBox)
        self.horizontalLayout_20.addWidget(self.frame_5)
        self.verticalLayout_22.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_19)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_23.setSpacing(12)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.Generate_btn_main = QtWidgets.QPushButton(self.frame_4)
        self.Generate_btn_main.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Generate_btn_main.setStyleSheet("padding:13px;")
        self.Generate_btn_main.setIcon(icon2)
        self.Generate_btn_main.setObjectName("Generate_btn_main")
        self.verticalLayout_23.addWidget(self.Generate_btn_main, 0, QtCore.Qt.AlignHCenter)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Pass_create_label = QtWidgets.QLabel(self.frame_8)
        self.Pass_create_label.setObjectName("Pass_create_label")
        self.horizontalLayout_7.addWidget(self.Pass_create_label)
        self.Copy_pass_main = QtWidgets.QPushButton(self.frame_8)
        self.Copy_pass_main.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Copy_pass_main.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/fd5028/feather/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Copy_pass_main.setIcon(icon12)
        self.Copy_pass_main.setObjectName("Copy_pass_main")
        self.horizontalLayout_7.addWidget(self.Copy_pass_main)
        self.verticalLayout_23.addWidget(self.frame_8)
        self.verticalLayout_22.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.verticalLayout_12.addWidget(self.frame_19)
        self.stackedWidget.addWidget(self.Create_pass)
        self.About_Page = QtWidgets.QWidget()
        self.About_Page.setObjectName("About_Page")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.About_Page)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_21 = QtWidgets.QFrame(self.About_Page)
        self.frame_21.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    border: 2px solid  white;\n"
"    padding: 5px;\n"
"color:white;}\n"
"QLabel{\n"
"border:0px;\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.frame_21)
        self.label_14.setMinimumSize(QtCore.QSize(40, 40))
        self.label_14.setMaximumSize(QtCore.QSize(40, 40))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/icons/Icons/feather/info.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.label_10 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addWidget(self.frame_21, 0, QtCore.Qt.AlignHCenter)
        self.frame_20 = QtWidgets.QFrame(self.About_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_20.setFont(font)
        self.frame_20.setStyleSheet("QLabel{\n"
"border:2px solid white;\n"
"padding:8px;\n"
"border-radius:5px;\n"
"\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_19 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_31.addWidget(self.label_19, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_13.addWidget(self.frame_20)
        self.stackedWidget.addWidget(self.About_Page)
        self.History_Page = QtWidgets.QWidget()
        self.History_Page.setObjectName("History_Page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.History_Page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_23 = QtWidgets.QFrame(self.History_Page)
        self.frame_23.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    border: 2px solid  white;\n"
"    padding: 5px;\n"
"color:white;}\n"
"QLabel{\n"
"border:0px;\n"
"}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_13.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.frame_23)
        self.label_16.setMinimumSize(QtCore.QSize(40, 40))
        self.label_16.setMaximumSize(QtCore.QSize(40, 40))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/icons/Icons/feather/hard-drive.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.label_11 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.frame_23, 0, QtCore.Qt.AlignHCenter)
        self.frame_22 = QtWidgets.QFrame(self.History_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setStyleSheet("QFrame{\n"
"border:2px solid white;\n"
"border-radius:10px;\n"
"color:white;}\n"
"QLabel{\n"
"padding:15px;\n"
"border:2px solid white;\n"
"border-radius:10px;\n"
"}\n"
"#label_17{\n"
"border:0px;}\n"
"\n"
"QPushButton{\n"
"    background-color:#141C24;\n"
"    border : 2px solid #00FFFF;\n"
"    padding:5px;\n"
"    border-radius:10px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #394B5A;\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.your_passwords_db = QtWidgets.QLabel(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.your_passwords_db.setFont(font)
        self.your_passwords_db.setObjectName("your_passwords_db")
        self.verticalLayout_30.addWidget(self.your_passwords_db, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_11 = QtWidgets.QFrame(self.frame_22)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_24.addWidget(self.label_17)
        self.Copy_all_pass_db = QtWidgets.QPushButton(self.frame_11)
        self.Copy_all_pass_db.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Copy_all_pass_db.setText("")
        self.Copy_all_pass_db.setIcon(icon6)
        self.Copy_all_pass_db.setObjectName("Copy_all_pass_db")
        self.horizontalLayout_24.addWidget(self.Copy_all_pass_db)
        self.verticalLayout_30.addWidget(self.frame_11, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.verticalLayout_6.addWidget(self.frame_22)
        self.stackedWidget.addWidget(self.History_Page)
        self.Check_pass = QtWidgets.QWidget()
        self.Check_pass.setObjectName("Check_pass")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.Check_pass)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_25 = QtWidgets.QFrame(self.Check_pass)
        self.frame_25.setStyleSheet("QFrame{\n"
"    border-radius: 10px;\n"
"    border: 2px solid  white;\n"
"    padding: 5px;\n"
"color:white;}\n"
"QLabel{\n"
"border:0px;\n"
"}")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_6 = QtWidgets.QLabel(self.frame_25)
        self.label_6.setMinimumSize(QtCore.QSize(40, 40))
        self.label_6.setMaximumSize(QtCore.QSize(40, 40))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/Icons/feather/check-square.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_19.addWidget(self.label_6)
        self.label_13 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_19.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_19.addWidget(self.frame_25, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_24 = QtWidgets.QFrame(self.Check_pass)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_24.sizePolicy().hasHeightForWidth())
        self.frame_24.setSizePolicy(sizePolicy)
        self.frame_24.setStyleSheet("")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.frame_33 = QtWidgets.QFrame(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_33.sizePolicy().hasHeightForWidth())
        self.frame_33.setSizePolicy(sizePolicy)
        self.frame_33.setStyleSheet("#frame_36{\n"
"border:2px solid white;\n"
"border-radius:7px;\n"
"color:white;\n"
"margin-top:7px;\n"
"padding:5px;\n"
"}\n"
"\n"
"\n"
"#label_32{\n"
"padding:10px;\n"
"border:2px solid white;\n"
"border-radius:10px;\n"
"color:white;\n"
"margin :7px;}\n"
"QLineEdit {\n"
"    border-radius: 10px;\n"
"    border: 2px solid #ccc;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton{\n"
"    background-color:#141C24;\n"
"    border : 2px solid #00FFFF;\n"
"    padding:5px;\n"
"    border-radius:10px;\n"
"color:white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #394B5A;\n"
"}")
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_35.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.frame_34 = QtWidgets.QFrame(self.frame_33)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.frame_35 = QtWidgets.QFrame(self.frame_34)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_32 = QtWidgets.QLabel(self.frame_35)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_33.addWidget(self.label_32, 0, QtCore.Qt.AlignVCenter)
        self.Input_password_check = QtWidgets.QLineEdit(self.frame_35)
        self.Input_password_check.setObjectName("Input_password_check")
        self.horizontalLayout_33.addWidget(self.Input_password_check)
        self.verticalLayout_36.addWidget(self.frame_35, 0, QtCore.Qt.AlignHCenter)
        self.check_pass_input = QtWidgets.QPushButton(self.frame_34)
        self.check_pass_input.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_pass_input.setObjectName("check_pass_input")
        self.verticalLayout_36.addWidget(self.check_pass_input, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_35.addWidget(self.frame_34, 0, QtCore.Qt.AlignHCenter)
        self.frame_36 = QtWidgets.QFrame(self.frame_33)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.frame_37 = QtWidgets.QFrame(self.frame_36)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_33 = QtWidgets.QLabel(self.frame_37)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_34.addWidget(self.label_33)
        self.length_check = QtWidgets.QLabel(self.frame_37)
        self.length_check.setMinimumSize(QtCore.QSize(40, 40))
        self.length_check.setMaximumSize(QtCore.QSize(40, 40))
        self.length_check.setText("")
        self.length_check.setPixmap(QtGui.QPixmap(":/icons/Icons/feather/x-circle.png"))
        self.length_check.setScaledContents(True)
        self.length_check.setObjectName("length_check")
        self.horizontalLayout_34.addWidget(self.length_check)
        self.verticalLayout_37.addWidget(self.frame_37, 0, QtCore.Qt.AlignHCenter)
        self.frame_38 = QtWidgets.QFrame(self.frame_36)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.frame_38)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setSpacing(0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_35 = QtWidgets.QLabel(self.frame_38)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_35.addWidget(self.label_35)
        self.complexity_check = QtWidgets.QLabel(self.frame_38)
        self.complexity_check.setMinimumSize(QtCore.QSize(40, 40))
        self.complexity_check.setMaximumSize(QtCore.QSize(40, 40))
        self.complexity_check.setText("")
        self.complexity_check.setPixmap(QtGui.QPixmap(":/icons/Icons/feather/x-circle.png"))
        self.complexity_check.setScaledContents(True)
        self.complexity_check.setObjectName("complexity_check")
        self.horizontalLayout_35.addWidget(self.complexity_check, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_37.addWidget(self.frame_38, 0, QtCore.Qt.AlignHCenter)
        self.frame_39 = QtWidgets.QFrame(self.frame_36)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_39)
        self.horizontalLayout_36.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_37 = QtWidgets.QLabel(self.frame_39)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_36.addWidget(self.label_37)
        self.Comman_p_check = QtWidgets.QLabel(self.frame_39)
        self.Comman_p_check.setMinimumSize(QtCore.QSize(40, 40))
        self.Comman_p_check.setMaximumSize(QtCore.QSize(40, 40))
        self.Comman_p_check.setText("")
        self.Comman_p_check.setPixmap(QtGui.QPixmap(":/icons/Icons/feather/x-circle.png"))
        self.Comman_p_check.setScaledContents(True)
        self.Comman_p_check.setObjectName("Comman_p_check")
        self.horizontalLayout_36.addWidget(self.Comman_p_check)
        self.verticalLayout_37.addWidget(self.frame_39, 0, QtCore.Qt.AlignHCenter)
        self.frame_40 = QtWidgets.QFrame(self.frame_36)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_37.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_39 = QtWidgets.QLabel(self.frame_40)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_37.addWidget(self.label_39)
        self.Dict_check = QtWidgets.QLabel(self.frame_40)
        self.Dict_check.setMinimumSize(QtCore.QSize(40, 40))
        self.Dict_check.setMaximumSize(QtCore.QSize(40, 40))
        self.Dict_check.setText("")
        self.Dict_check.setPixmap(QtGui.QPixmap(":/icons/Icons/feather/x-circle.png"))
        self.Dict_check.setScaledContents(True)
        self.Dict_check.setObjectName("Dict_check")
        self.horizontalLayout_37.addWidget(self.Dict_check)
        self.verticalLayout_37.addWidget(self.frame_40, 0, QtCore.Qt.AlignHCenter)
        self.frame_41 = QtWidgets.QFrame(self.frame_36)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_41)
        self.horizontalLayout_38.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_41 = QtWidgets.QLabel(self.frame_41)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_38.addWidget(self.label_41)
        self.SCC_check = QtWidgets.QLabel(self.frame_41)
        self.SCC_check.setMinimumSize(QtCore.QSize(40, 40))
        self.SCC_check.setMaximumSize(QtCore.QSize(40, 40))
        self.SCC_check.setText("")
        self.SCC_check.setPixmap(QtGui.QPixmap(":/icons/Icons/feather/x-circle.png"))
        self.SCC_check.setScaledContents(True)
        self.SCC_check.setObjectName("SCC_check")
        self.horizontalLayout_38.addWidget(self.SCC_check)
        self.verticalLayout_37.addWidget(self.frame_41, 0, QtCore.Qt.AlignHCenter)
        self.frame_42 = QtWidgets.QFrame(self.frame_36)
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_42)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_43 = QtWidgets.QLabel(self.frame_42)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_26.addWidget(self.label_43)
        self.Final_review_check = QtWidgets.QLabel(self.frame_42)
        self.Final_review_check.setObjectName("Final_review_check")
        self.horizontalLayout_26.addWidget(self.Final_review_check)
        self.verticalLayout_37.addWidget(self.frame_42, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_35.addWidget(self.frame_36, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_39.addWidget(self.frame_33)
        self.verticalLayout_19.addWidget(self.frame_24)
        self.stackedWidget.addWidget(self.Check_pass)
        self.verticalLayout_8.addWidget(self.stackedWidget)
        self.verticalLayout_4.addWidget(self.Main_body)
        self.Footer = QtWidgets.QFrame(self.Main_Panel)
        self.Footer.setStyleSheet("QFrame {\n"
"    background-color: #141C24  ;\n"
"    border:0px;\n"
"}\n"
"\n"
"QLabel{\n"
"color:white;\n"
"border:0px;}")
        self.Footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Footer.setObjectName("Footer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Footer)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Creator_Name = QtWidgets.QFrame(self.Footer)
        self.Creator_Name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Creator_Name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Creator_Name.setObjectName("Creator_Name")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Creator_Name)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Size_Grip_Frame = QtWidgets.QFrame(self.Creator_Name)
        self.Size_Grip_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Size_Grip_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Size_Grip_Frame.setObjectName("Size_Grip_Frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Size_Grip_Frame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Size_Grip = QtWidgets.QFrame(self.Size_Grip_Frame)
        self.Size_Grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Size_Grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Size_Grip.setObjectName("Size_Grip")
        self.verticalLayout_9.addWidget(self.Size_Grip)
        self.verticalLayout_7.addWidget(self.Size_Grip_Frame)
        self.My_Name = QtWidgets.QLabel(self.Creator_Name)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.My_Name.setFont(font)
        self.My_Name.setObjectName("My_Name")
        self.verticalLayout_7.addWidget(self.My_Name, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addWidget(self.Creator_Name, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.Footer)
        self.horizontalLayout.addWidget(self.Main_Panel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Name_of_app.setText(_translate("MainWindow", "PassGenPro "))
        self.Sign_Up_btn.setText(_translate("MainWindow", "Sign Up"))
        self.Login_In_btn.setText(_translate("MainWindow", "Login"))
        self.Create_pass_btn.setText(_translate("MainWindow", "Create a Password"))
        self.Check_pass_btn.setText(_translate("MainWindow", "Check Strength"))
        self.History_btn.setText(_translate("MainWindow", "Your Passwords"))
        self.About_btn.setText(_translate("MainWindow", "About"))
        self.Name_Menu.setText(_translate("MainWindow", "Menu"))
        self.Name.setText(_translate("MainWindow", "DashBoard"))
        self.UserName_Display.setText(_translate("MainWindow", "Guest"))
        self.label_12.setText(_translate("MainWindow", "Sign Up"))
        self.label.setText(_translate("MainWindow", "UserName"))
        self.User_Info_Input.setPlaceholderText(_translate("MainWindow", "UserName"))
        self.label_4.setText(_translate("MainWindow", "E-Mail"))
        self.EMail_input.setPlaceholderText(_translate("MainWindow", "E-Mail"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.Pass_input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "Re-Enter Password"))
        self.Re_enter_pass_input.setPlaceholderText(_translate("MainWindow", "Re-Enter"))
        self.Sign_up_btn.setText(_translate("MainWindow", "Sign Up"))
        self.label_15.setText(_translate("MainWindow", "Login"))
        self.label_18.setText(_translate("MainWindow", "UserName"))
        self.Username_input_login.setPlaceholderText(_translate("MainWindow", "UserName"))
        self.label_20.setText(_translate("MainWindow", "Password"))
        self.Pass_input_login.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Login_Check_btn.setText(_translate("MainWindow", "Login"))
        self.label_9.setText(_translate("MainWindow", "Create a Password"))
        self.Label_input_pass.setText(_translate("MainWindow", "Length of Password"))
        self.Input_pass_Lineedit.setPlaceholderText(_translate("MainWindow", "Enter the Length"))
        self.Complexity_label_main.setText(_translate("MainWindow", "Complexity level"))
        self.Pass_complexity.setItemText(0, _translate("MainWindow", "Easy"))
        self.Pass_complexity.setItemText(1, _translate("MainWindow", "Medium"))
        self.Pass_complexity.setItemText(2, _translate("MainWindow", "Hard"))
        self.Pass_complexity.setItemText(3, _translate("MainWindow", "Very Hard"))
        self.Easy_char_box.setText(_translate("MainWindow", "Use simple characters (! $ @ #)"))
        self.Medium_char_box.setText(_translate("MainWindow", "Use medium characters (% ^  ? *)"))
        self.Hard_char_box.setText(_translate("MainWindow", "Use hard characters ( _ - + = )"))
        self.VHard_char_box.setText(_translate("MainWindow", "Use very hard characters ( ~ ` | / )"))
        self.Generate_btn_main.setText(_translate("MainWindow", "Generate"))
        self.Pass_create_label.setText(_translate("MainWindow", "Click Generate to Generate a password here!"))
        self.label_10.setText(_translate("MainWindow", "About"))
        self.label_19.setText(_translate("MainWindow", "🔐 Welcome to PassGenPro - your ultimate password generator and manager! Powered by Python & PyQt5, effortlessly create passwords tailored to your needs - whether strong, weak, very strong, or medium. 💪 Choose from a variety of special characters and customize the length of your password with ease.\n"
"\n"
"🔍 Want to check your password\'s strength? PassGenPro has you covered! Get insights with Length Check, Complexity Check, Avoid Common Patterns Check, Dictionary Check, and Avoid Sequential Characters Check, all with the help of pwnedpasswords.\n"
"\n"
"🔒 But security doesn\'t end there. PassGenPro also offers a secure password manager, allowing you to store your passwords safely when creating or logging into existing accounts.\n"
"\n"
"🎨 With its unique and attractive GUI, PassGenPro revolutionizes password management, making it not just secure, but also a pleasure to use.\n"
"\n"
"💡 Experience the future of password management with PassGenPro! Download now and take control of your digital security with style. 🌟"))
        self.label_11.setText(_translate("MainWindow", "Your Passwords"))
        self.your_passwords_db.setText(_translate("MainWindow", "🔒 Secure your passwords by Logging In to store them in a database! 🛡️"))
        self.label_17.setText(_translate("MainWindow", "📋Copy all your passwords! "))
        self.label_13.setText(_translate("MainWindow", "Check Your Password Strength"))
        self.label_32.setText(_translate("MainWindow", "Enter Your Password:"))
        self.Input_password_check.setPlaceholderText(_translate("MainWindow", "Password"))
        self.check_pass_input.setText(_translate("MainWindow", "Check Password 🔑"))
        self.label_33.setText(_translate("MainWindow", "Length Check: "))
        self.label_35.setText(_translate("MainWindow", "Complexity Check:"))
        self.label_37.setText(_translate("MainWindow", "Avoid Common Patterns Check: "))
        self.label_39.setText(_translate("MainWindow", "Dictionary Check: "))
        self.label_41.setText(_translate("MainWindow", "Avoid Sequential Characters Check: "))
        self.label_43.setText(_translate("MainWindow", "Final Review : "))
        self.Final_review_check.setText(_translate("MainWindow", "----"))
        self.My_Name.setText(_translate("MainWindow", "Made By Chaitanya Saradhi"))

        self.controller = AppController(
        self.User_Info_Input,
        self.EMail_input,
        self.Pass_input,
        self.Re_enter_pass_input,
        self.Username_input_login,
        self.Pass_input_login,
        self.Sign_Up_info_after_check,
        self.Login_info_after_check,
        self.UserName_Display,
        self.GitHub_link,
        self.LinkedIn_Link,
        self.Easy_char_box,
        self.Medium_char_box,
        self.Hard_char_box,
        self.VHard_char_box,
        self.Pass_complexity,
        self.Input_pass_Lineedit,
        self.Pass_create_label,
        self.your_passwords_db,
        self.Input_password_check,
        self.length_check,
        self.complexity_check,
        self.Comman_p_check,
        self.SCC_check,
        self.Final_review_check
        )
        self.Sign_up_btn.clicked.connect(self.controller.sign_up)
        self.Login_Check_btn.clicked.connect(self.controller.login)
        self.GitHub_link.clicked.connect(self.controller.link_copier.copy_github_link)
        self.LinkedIn_Link.clicked.connect(self.controller.link_copier.copy_linkedin_link)
        self.Copy_pass_main.clicked.connect(self.controller.Copy_password)
        self.Generate_btn_main.clicked.connect(self.controller.generate_password)
        self.Copy_all_pass_db.clicked.connect(self.controller.get_passwords_from_label)
        self.check_pass_input.clicked.connect(self.controller.process_password_strength)


from Custom_Widgets.QCustomSlideMenu import QCustomSlideMenu
